image: test.makerforce.io:8443/build-images/ubuntu-nodejs:master

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker info
  - git submodule init
  - git submodule update

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - echo "Fetching dependencies..."
    - npm install
    - echo "Building assets..."
    - node node_modules/grunt-cli/bin/grunt
    - echo "Building container..."
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  script:
    - 
